version: '3.8'

services:
    frontend:
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/app:cached
            - /app/node_modules
            - /app/dist
        command: npm run dev
        ports:
            - '5173:5173'
        environment:
            - NODE_ENV=development
        container_name: volleyball-frontend-dev

    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        volumes:
            - ./backend:/app:cached
        command: npm run dev
        ports:
            - '5000:5000'
        environment:
            - NODE_ENV=development
        env_file:
            - ./backend/.env
        container_name: volleyball-backend
        depends_on:
            - frontend
